### ISSUE TITLE
这个线上考试系统怎么运行，有偿

### ISSUE THREAD

**Issue by AtistZero** [xausee/ExamSystem#1]

**Comment by AtistZero** [comment]
这个运行环境有什么要求吗。作者大人能帮忙解决一下吗，有偿的！

**Comment by YiXiaoCuoHuaiFenZi** [comment]
汗颜，快过一年了才注意到，现在还需要吗，reademe 里面都有详细的安装执行步骤，如果还是有问题，在这里回复一下。免费帮你在windows或者mac 电脑上装好。

**Comment by Acechen2** [comment]
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0xe14bcf]
运行时提示这个怎么办，求助！！！

**Comment by YiXiaoCuoHuaiFenZi** [comment]
> panic: runtime error: invalid memory address or nil pointer dereference [signal 0xc0000005 code=0x0 addr=0x0 pc=0xe14bcf] 运行时提示这个怎么办，求助！！！

这个报错看不出是哪里的问题，把全部报错堆栈发出来看看，另外可以加我微信方便些 
![image](https://github.com/YiXiaoCuoHuaiFenZi/examsystem/assets/33883485/7efef655-1ca8-4357-83e0-fdb9759726cc)
