### ISSUE TITLE
这个源码没有main包，不会运行

### ISSUE THREAD

**Issue by AtistZero** [xausee/ExamSystem#2]

**Comment by YiXiaoCuoHuaiFenZi** [comment]
这个是基于revel框架的，里面包含了入口函数，只需要按readme里的步骤一步一步执行就可以运行
![image](https://github.com/YiXiaoCuoHuaiFenZi/examsystem/assets/33883485/3de1ca6f-8499-4b9f-91ca-ed39a0399b95)
